name: slack_notifier
description: A simple wrapper for posting messages to Slack using Incoming Webhooks.
version: 1.3.0
homepage: https://github.com/javoeria/slack-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
